// deliveroo/customer-portal/pages/dashboard/settings.vue
<template>
  <div>
    <div class="mb-8">
      <h1 class="text-2xl font-bold text-gray-900 dark:text-white">
        Settings
      </h1>
      <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
        Manage your account and company settings
      </p>
    </div>

    <!-- Tab Navigation -->
    <div class="border-b border-gray-200 dark:border-gray-700 mb-8">
      <nav class="-mb-px flex space-x-8" aria-label="Tabs">
        <button
          v-for="tab in tabs"
          :key="tab.id"
          @click="activeTab = tab.id"
          :class="[
            activeTab === tab.id
              ? 'border-success-500 text-success-600 dark:text-success-400'
              : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 dark:text-gray-400 dark:hover:text-gray-300',
            'whitespace-nowrap py-2 px-1 border-b-2 font-medium text-sm transition-colors'
          ]"
        >
          <component :is="tab.icon" class="w-5 h-5 mr-2 inline" />
          {{ tab.name }}
        </button>
      </nav>
    </div>

    <!-- Tab Content -->
    <div class="space-y-8">
      <!-- Company Information Tab -->
      <div v-show="activeTab === 'company'" class="card p-6">
        <h2 class="text-lg font-medium text-gray-900 dark:text-white mb-6">
          Company Information
        </h2>
        
        <form @submit.prevent="updateCompanyInfo" class="space-y-6">
          <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Company Name *
              </label>
              <input
                v-model="companyForm.name"
                type="text"
                required
                class="input"
              />
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Registration Number *
              </label>
              <input
                v-model="companyForm.registrationNumber"
                type="text"
                required
                class="input"
              />
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                VAT Number
              </label>
              <input
                v-model="companyForm.vatNumber"
                type="text"
                class="input"
              />
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Industry Type
              </label>
              <select
                v-model="companyForm.industryType"
                class="input"
              >
                <option value="Manufacturing">Manufacturing</option>
                <option value="Retail">Retail</option>
                <option value="Automotive">Automotive</option>
                <option value="Food & Beverage">Food & Beverage</option>
                <option value="Technology">Technology</option>
                <option value="Healthcare">Healthcare</option>
                <option value="Other">Other</option>
              </select>
            </div>
          </div>
          
          <div>
            <h3 class="text-md font-medium text-gray-900 dark:text-white mb-4">
              Company Address
            </h3>
            <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
              <div class="sm:col-span-2">
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Street Address *
                </label>
                <input
                  v-model="companyForm.address.street"
                  type="text"
                  required
                  class="input"
                />
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  City *
                </label>
                <input
                  v-model="companyForm.address.city"
                  type="text"
                  required
                  class="input"
                />
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Postal Code *
                </label>
                <input
                  v-model="companyForm.address.postalCode"
                  type="text"
                  required
                  class="input"
                />
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Country *
                </label>
                <select
                  v-model="companyForm.address.country"
                  required
                  class="input"
                >
                  <option value="Poland">Poland</option>
                  <option value="Germany">Germany</option>
                  <option value="Czech Republic">Czech Republic</option>
                  <option value="Slovakia">Slovakia</option>
                  <option value="Hungary">Hungary</option>
                </select>
              </div>
            </div>
          </div>
          
          <div class="flex justify-end">
            <button
              type="submit"
              class="btn-primary"
            >
              Save Company Information
            </button>
          </div>
        </form>
      </div>

      <!-- Contact Information Tab -->
      <div v-show="activeTab === 'contact'" class="card p-6">
        <h2 class="text-lg font-medium text-gray-900 dark:text-white mb-6">
          Contact Information
        </h2>
        
        <form @submit.prevent="updateContactInfo" class="space-y-6">
          <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Primary Email *
              </label>
              <input
                v-model="contactForm.primaryEmail"
                type="email"
                required
                class="input"
              />
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Primary Phone *
              </label>
              <input
                v-model="contactForm.primaryPhone"
                type="tel"
                required
                class="input"
              />
            </div>
            
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                Website
              </label>
              <input
                v-model="contactForm.website"
                type="url"
                class="input"
                placeholder="https://example.com"
              />
            </div>
          </div>
          
          <div>
            <h3 class="text-md font-medium text-gray-900 dark:text-white mb-4">
              Emergency Contact
            </h3>
            <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Contact Name *
                </label>
                <input
                  v-model="contactForm.emergencyContact.name"
                  type="text"
                  required
                  class="input"
                />
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Contact Phone *
                </label>
                <input
                  v-model="contactForm.emergencyContact.phone"
                  type="tel"
                  required
                  class="input"
                />
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Contact Email
                </label>
                <input
                  v-model="contactForm.emergencyContact.email"
                  type="email"
                  class="input"
                />
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Relationship
                </label>
                <input
                  v-model="contactForm.emergencyContact.relationship"
                  type="text"
                  class="input"
                  placeholder="e.g., Manager, Director"
                />
              </div>
            </div>
          </div>
          
          <div class="flex justify-end">
            <button
              type="submit"
              class="btn-primary"
            >
              Save Contact Information
            </button>
          </div>
        </form>
      </div>

      <!-- Notification Preferences Tab -->
      <div v-show="activeTab === 'notifications'" class="card p-6">
        <h2 class="text-lg font-medium text-gray-900 dark:text-white mb-6">
          Notification Preferences
        </h2>
        
        <form @submit.prevent="updateNotificationPreferences" class="space-y-6">
          <div class="space-y-4">
            <div class="flex items-center justify-between">
              <div>
                <h3 class="text-sm font-medium text-gray-900 dark:text-white">
                  Email Notifications
                </h3>
                <p class="text-sm text-gray-500 dark:text-gray-400">
                  Receive updates about your shipments and requests
                </p>
              </div>
              <label class="relative inline-flex items-center cursor-pointer">
                <input
                  v-model="notificationForm.emailNotifications"
                  type="checkbox"
                  class="sr-only peer"
                />
                <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-success-300 dark:peer-focus:ring-success-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-success-600"></div>
              </label>
            </div>
            
            <div class="flex items-center justify-between">
              <div>
                <h3 class="text-sm font-medium text-gray-900 dark:text-white">
                  SMS Notifications
                </h3>
                <p class="text-sm text-gray-500 dark:text-gray-400">
                  Receive critical updates via SMS
                </p>
              </div>
              <label class="relative inline-flex items-center cursor-pointer">
                <input
                  v-model="notificationForm.smsNotifications"
                  type="checkbox"
                  class="sr-only peer"
                />
                <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-success-300 dark:peer-focus:ring-success-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-success-600"></div>
              </label>
            </div>
            
            <div class="flex items-center justify-between">
              <div>
                <h3 class="text-sm font-medium text-gray-900 dark:text-white">
                  Marketing Communications
                </h3>
                <p class="text-sm text-gray-500 dark:text-gray-400">
                  Receive newsletters and promotional offers
                </p>
              </div>
              <label class="relative inline-flex items-center cursor-pointer">
                <input
                  v-model="notificationForm.marketingCommunications"
                  type="checkbox"
                  class="sr-only peer"
                />
                <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-success-300 dark:peer-focus:ring-success-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-success-600"></div>
              </label>
            </div>
          </div>
          
          <div class="flex justify-end">
            <button
              type="submit"
              class="btn-primary"
            >
              Save Preferences
            </button>
          </div>
        </form>
      </div>

      <!-- Security Settings Tab -->
      <div v-show="activeTab === 'security'" class="card p-6">
        <h2 class="text-lg font-medium text-gray-900 dark:text-white mb-6">
          Security Settings
        </h2>
        
        <div class="space-y-6">
          <div>
            <h3 class="text-md font-medium text-gray-900 dark:text-white mb-4">
              Change Password
            </h3>
            <form @submit.prevent="changePassword" class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Current Password
                </label>
                <input
                  v-model="passwordForm.currentPassword"
                  type="password"
                  required
                  class="input"
                />
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  New Password
                </label>
                <input
                  v-model="passwordForm.newPassword"
                  type="password"
                  required
                  class="input"
                />
              </div>
              
              <div>
                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Confirm New Password
                </label>
                <input
                  v-model="passwordForm.confirmPassword"
                  type="password"
                  required
                  class="input"
                />
              </div>
              
              <div class="flex justify-end">
                <button
                  type="submit"
                  class="btn-primary"
                >
                  Change Password
                </button>
              </div>
            </form>
          </div>
          
          <div class="border-t border-gray-200 dark:border-gray-700 pt-6">
            <h3 class="text-md font-medium text-gray-900 dark:text-white mb-4">
              Two-Factor Authentication
            </h3>
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm text-gray-600 dark:text-gray-300">
                  Add an extra layer of security to your account
                </p>
              </div>
              <button class="btn-outline">
                Enable 2FA
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  BuildingOfficeIcon,
  PhoneIcon,
  BellIcon,
  ShieldCheckIcon
} from '@heroicons/vue/24/outline'

const activeTab = ref('company')

const tabs = [
  { id: 'company', name: 'Company Information', icon: BuildingOfficeIcon },
  { id: 'contact', name: 'Contact Information', icon: PhoneIcon },
  { id: 'notifications', name: 'Notifications', icon: BellIcon },
  { id: 'security', name: 'Security', icon: ShieldCheckIcon }
]

const companyForm = reactive({
  name: 'Example Logistics Ltd.',
  registrationNumber: 'PL1234567890',
  vatNumber: 'PL1234567890',
  industryType: 'Manufacturing',
  address: {
    street: 'ul. Logistyczna 123',
    city: 'Warsaw',
    postalCode: '00-001',
    country: 'Poland'
  }
})

const contactForm = reactive({
  primaryEmail: 'contact@example.com',
  primaryPhone: '+48123456789',
  website: 'https://example.com',
  emergencyContact: {
    name: 'Emergency Contact',
    phone: '+48987654321',
    email: 'emergency@example.com',
    relationship: 'Manager'
  }
})

const notificationForm = reactive({
  emailNotifications: true,
  smsNotifications: false,
  marketingCommunications: true
})

const passwordForm = reactive({
  currentPassword: '',
  newPassword: '',
  confirmPassword: ''
})

const updateCompanyInfo = async () => {
  try {
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000))
    console.log('Company information updated')
  } catch (error) {
    console.error('Failed to update company information:', error)
  }
}

const updateContactInfo = async () => {
  try {
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000))
    console.log('Contact information updated')
  } catch (error) {
    console.error('Failed to update contact information:', error)
  }
}

const updateNotificationPreferences = async () => {
  try {
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000))
    console.log('Notification preferences updated')
  } catch (error) {
    console.error('Failed to update notification preferences:', error)
  }
}

const changePassword = async () => {
  if (passwordForm.newPassword !== passwordForm.confirmPassword) {
    alert('New passwords do not match')
    return
  }
  
  try {
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000))
    
    // Reset form
    passwordForm.currentPassword = ''
    passwordForm.newPassword = ''
    passwordForm.confirmPassword = ''
    
    console.log('Password changed successfully')
  } catch (error) {
    console.error('Failed to change password:', error)
  }
}

definePageMeta({
  layout: 'dashboard',
  middleware: 'auth'
})
</script>

// deliveroo/wms-frontend/src/app/settings/settings.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../auth/auth.service';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { UserProfile } from '../user-management/user.model';
import { NotificationService } from '../notifications/notification.service';
import { LucideAngularModule, User, Mail, Phone, Shield, Save, Eye, EyeOff } from 'lucide-angular';

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  template: `
    <div class="space-y-6">
      <!-- Header -->
      <div>
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">Settings</h1>
        <p class="text-gray-600 dark:text-gray-400">Manage your account settings and preferences</p>
      </div>

      <!-- Profile Settings -->
      <div class="card p-6">
        <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-6 flex items-center">
          <lucide-icon [img]="UserIcon" size="20" class="mr-2"></lucide-icon>
          Profile Information
        </h3>

        <form (ngSubmit)="saveProfile()" #profileForm="ngForm">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <!-- Avatar Section -->
            <div class="md:col-span-2 flex items-center space-x-6">
              <div class="flex-shrink-0">
                <div class="h-20 w-20 rounded-full bg-primary-100 flex items-center justify-center">
                  <span class="text-2xl font-medium text-primary-600">{{ currentUser?.name?.charAt(0) || 'U' }}</span>
                </div>
              </div>
              <div>
                <h4 class="text-lg font-medium text-gray-900 dark:text-white">Profile Picture</h4>
                <p class="text-sm text-gray-500 dark:text-gray-400">Update your profile picture</p>
                <button type="button" class="mt-2 btn btn-secondary">
                  Change Avatar
                </button>
              </div>
            </div>

            <!-- Full Name -->
            <div>
              <label for="fullName" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Full Name
              </label>
              <div class="relative">
                <lucide-icon [img]="UserIcon" size="18" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400"></lucide-icon>
                <input type="text" 
                       id="fullName"
                       name="fullName"
                       [(ngModel)]="profileData.fullName"
                       class="input pl-10"
                       required>
              </div>
            </div>

            <!-- Email -->
            <div>
              <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Email Address
              </label>
              <div class="relative">
                <lucide-icon [img]="MailIcon" size="18" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400"></lucide-icon>
                <input type="email" 
                       id="email"
                       name="email"
                       [(ngModel)]="profileData.email"
                       class="input pl-10"
                       required>
              </div>
            </div>

            <!-- Phone -->
            <div>
              <label for="phone" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Phone Number
              </label>
              <div class="relative">
                <lucide-icon [img]="PhoneIcon" size="18" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400"></lucide-icon>
                <input type="tel" 
                       id="phone"
                       name="phone"
                       [(ngModel)]="profileData.phone"
                       class="input pl-10">
              </div>
            </div>

            <!-- Role (Read-only) -->
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Current Role
              </label>
              <div class="relative">
                <lucide-icon [img]="ShieldIcon" size="18" class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400"></lucide-icon>
                <input type="text" 
                       [value]="getUserRole()"
                       class="input pl-10 bg-gray-50 dark:bg-dark-700"
                       readonly>
              </div>
            </div>
          </div>

          <div class="mt-6 flex justify-end">
            <button type="submit" 
                    [disabled]="!profileForm.form.valid || saving"
                    class="btn btn-primary">
              <lucide-icon [img]="SaveIcon" size="18" class="mr-2"></lucide-icon>
              {{ saving ? 'Saving...' : 'Save Changes' }}
            </button>
          </div>
        </form>
      </div>

      <!-- Security Settings -->
      <div class="card p-6">
        <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-6 flex items-center">
          <lucide-icon [img]="ShieldIcon" size="20" class="mr-2"></lucide-icon>
          Security Settings
        </h3>

        <form (ngSubmit)="changePassword()" #passwordForm="ngForm">
          <div class="space-y-6">
            <!-- Current Password -->
            <div>
              <label for="currentPassword" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Current Password
              </label>
              <div class="relative">
                <input [type]="showCurrentPassword ? 'text' : 'password'" 
                       id="currentPassword"
                       name="currentPassword"
                       [(ngModel)]="passwordData.currentPassword"
                       class="input pr-10"
                       required>
                <button type="button" 
                        (click)="showCurrentPassword = !showCurrentPassword"
                        class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600">
                  <lucide-icon [img]="showCurrentPassword ? EyeOffIcon : EyeIcon" size="18"></lucide-icon>
                </button>
              </div>
            </div>

            <!-- New Password -->
            <div>
              <label for="newPassword" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                New Password
              </label>
              <div class="relative">
                <input [type]="showNewPassword ? 'text' : 'password'" 
                       id="newPassword"
                       name="newPassword"
                       [(ngModel)]="passwordData.newPassword"
                       class="input pr-10"
                       required
                       minlength="8">
                <button type="button" 
                        (click)="showNewPassword = !showNewPassword"
                        class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600">
                  <lucide-icon [img]="showNewPassword ? EyeOffIcon : EyeIcon" size="18"></lucide-icon>
                </button>
              </div>
              <p class="mt-1 text-xs text-gray-500 dark:text-gray-400">
                Password must be at least 8 characters long
              </p>
            </div>

            <!-- Confirm Password -->
            <div>
              <label for="confirmPassword" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Confirm New Password
              </label>
              <div class="relative">
                <input [type]="showConfirmPassword ? 'text' : 'password'" 
                       id="confirmPassword"
                       name="confirmPassword"
                       [(ngModel)]="passwordData.confirmPassword"
                       class="input pr-10"
                       required>
                <button type="button" 
                        (click)="showConfirmPassword = !showConfirmPassword"
                        class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600">
                  <lucide-icon [img]="showConfirmPassword ? EyeOffIcon : EyeIcon" size="18"></lucide-icon>
                </button>
              </div>
              @if (passwordData.newPassword && passwordData.confirmPassword && passwordData.newPassword !== passwordData.confirmPassword) {
                <div class="mt-1 text-xs text-error-600">
                  Passwords do not match
                </div>
              }
            </div>
          </div>

          <div class="mt-6 flex justify-end">
            <button type="submit" 
                    [disabled]="!passwordForm.form.valid || passwordData.newPassword !== passwordData.confirmPassword || changingPassword"
                    class="btn btn-primary">
              <lucide-icon [img]="SaveIcon" size="18" class="mr-2"></lucide-icon>
              {{ changingPassword ? 'Changing...' : 'Change Password' }}
            </button>
          </div>
        </form>
      </div>

      <!-- Account Information -->
      <div class="card p-6">
        <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-6">Account Information</h3>
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <label class="text-sm font-medium text-gray-700 dark:text-gray-300">Account Created</label>
            <p class="text-sm text-gray-900 dark:text-white mt-1">{{ currentUser?.warehouseAssignments?.[0]?.assignedFrom | date:'MMM d, y' }}</p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-700 dark:text-gray-300">Last Login</label>
            <p class="text-sm text-gray-900 dark:text-white mt-1">{{ currentUser?.lastLogin | date:'MMM d, y h:mm a' }}</p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-700 dark:text-gray-300">Assigned Warehouse</label>
            <p class="text-sm text-gray-900 dark:text-white mt-1">{{ currentUser?.warehouseAssignments?.[0]?.warehouseName || 'N/A' }}</p>
          </div>
          <div>
            <label class="text-sm font-medium text-gray-700 dark:text-gray-300">Account Status</label>
            <span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-success-100 text-success-800 mt-1">
              Active
            </span>
          </div>
        </div>
      </div>
    </div>
  `
})
export class SettingsComponent implements OnInit {
  currentUser: UserProfile | null = null;
  saving = false;
  changingPassword = false;
  
  // Password visibility toggles
  showCurrentPassword = false;
  showNewPassword = false;
  showConfirmPassword = false;

  // Form data
  profileData = {
    fullName: '',
    email: '',
    phone: ''
  };

  passwordData = {
    currentPassword: '',
    newPassword: '',
    confirmPassword: ''
  };

  // Lucide icons
  UserIcon = User;
  MailIcon = Mail;
  PhoneIcon = Phone;
  ShieldIcon = Shield;
  SaveIcon = Save;
  EyeIcon = Eye;
  EyeOffIcon = EyeOff;

  private authService = inject(AuthService);

  ngOnInit(): void {
    this.currentUser = this.authService.currentUser();
    if (this.currentUser) {
      this.profileData = {
        fullName: this.currentUser.name,
        email: this.currentUser.email,
        phone: this.currentUser.phone || ''
      };
    }
  }

  getUserRole(): string {
    return this.currentUser?.role?.[0]?.roleName || 'N/A';
  }

  saveProfile(): void {
    this.saving = true;
    
    // Simulate API call
    setTimeout(() => {
      console.log('Profile saved:', this.profileData);
      this.saving = false;
      // Show success message
    }, 1000);
  }

  changePassword(): void {
    if (this.passwordData.newPassword !== this.passwordData.confirmPassword) {
      return;
    }

    this.changingPassword = true;
    
    // Simulate API call
    setTimeout(() => {
      console.log('Password changed');
      this.changingPassword = false;
      // Clear form
      this.passwordData = {
        currentPassword: '',
        newPassword: '',
        confirmPassword: ''
      };
      // Show success message
    }, 1000);
  }
}
