// deliveroo/customer-portal/pages/login.vue
<template>
  <div>
    <div class="text-center mb-6">
      <h2 class="text-3xl font-bold text-gray-900 dark:text-white">
        Sign in to your account
      </h2>
      <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
        Or
        <NuxtLink to="/register" class="font-medium text-primary-600 hover:text-primary-500 dark:text-primary-400">
          create a new company account
        </NuxtLink>
      </p>
    </div>

    <form @submit.prevent="handleLogin" class="space-y-6">
      <div>
        <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
          Email address
        </label>
        <input
          id="email"
          v-model="form.email"
          type="email"
          required
          autocomplete="email"
          class="input"
          placeholder="Enter your email"
        />
      </div>

      <div>
        <label for="password" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
          Password
        </label>
        <input
          id="password"
          v-model="form.password"
          type="password"
          required
          autocomplete="current-password"
          class="input"
          placeholder="Enter your password"
        />
      </div>

      <div class="flex items-center justify-between">
        <div class="flex items-center">
          <input
            id="remember-me"
            v-model="form.remember"
            type="checkbox"
            class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
          />
          <label for="remember-me" class="ml-2 block text-sm text-gray-900 dark:text-gray-300">
            Remember me
          </label>
        </div>

        <div class="text-sm">
          <a href="#" class="font-medium text-primary-600 hover:text-primary-500 dark:text-primary-400">
            Forgot your password?
          </a>
        </div>
      </div>

      <div>
        <button
          type="submit"
          :disabled="authStore.loading"
          class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          <span v-if="!authStore.loading">Sign in</span>
          <span v-else class="flex items-center">
            <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Signing in...
          </span>
        </button>
      </div>
    </form>

    <div class="mt-6">
      <div class="relative">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t border-gray-300 dark:border-gray-600" />
        </div>
        <div class="relative flex justify-center text-sm">
          <span class="px-2 bg-white dark:bg-gray-800 text-gray-500">Don't have an account?</span>
        </div>
      </div>

      <div class="mt-6">
        <NuxtLink
          to="/quote"
          class="w-full flex justify-center py-2 px-4 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          Get Quote as Guest
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const authStore = useAuthStore()

const form = reactive({
  email: '',
  password: '',
  remember: false
})

const handleLogin = async () => {
  try {
    await authStore.login({
      email: form.email,
      password: form.password
    })
  } catch (error) {
    // Handle error (show toast notification)
    console.error('Login failed:', error)
  }
}

definePageMeta({
  layout: 'auth'
})
</script>

// webinar-04-fullstack/deliveroo/deliveroo-frontend/src/app/features/auth/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  template: `
    <div class="min-h-screen bg-neutral-50 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
      <div class="max-w-md w-full bg-white rounded-lg shadow-lg p-8 animate-fade-in">
        <div class="text-center mb-8">
          <h2 class="text-3xl font-bold text-neutral-800">Welcome back</h2>
          <p class="mt-2 text-neutral-600">Sign in to your account</p>
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-6">
          <!-- Error message -->
          @if (error) {
            <div class="bg-error-50 text-error-500 p-3 rounded-md mb-4 animate-fade-in">
              {{ error }}
            </div>
          }

          <!-- Email/Username Field -->
          <div>
            <label for="email" class="form-label">Email or Username</label>
            <input 
              type="text" 
              id="email" 
              formControlName="email"
              class="form-control" 
              autocomplete="email" 
              [class.border-error-500]="isFieldInvalid('email')" />
            
            @if (isFieldInvalid('email')) {
              <p class="mt-1 text-sm text-error-500">Please enter a valid email or username</p>
            }
          </div>

          <!-- Password Field -->
          <div>
            <div class="flex justify-between items-center">
              <label for="password" class="form-label">Password</label>
              <a routerLink="/auth/forgot-password" class="text-sm text-primary-500 hover:text-primary-600 transition-colors">
                Forgot your password?
              </a>
            </div>
            <input 
              [type]="showPassword ? 'text' : 'password'" 
              id="password" 
              formControlName="password"
              class="form-control pr-10" 
              autocomplete="current-password"
              [class.border-error-500]="isFieldInvalid('password')" />
            
            @if (isFieldInvalid('password')) {
              <p class="mt-1 text-sm text-error-500">Password is required</p>
            }
          </div>

          <!-- Remember Me Checkbox -->
          <div class="flex items-center">
            <input 
              id="remember-me" 
              name="remember-me" 
              type="checkbox"
              formControlName="rememberMe"
              class="h-4 w-4 text-primary-500 border-neutral-300 rounded focus:ring-primary-500" />
            <label for="remember-me" class="ml-2 block text-sm text-neutral-700">
              Remember me
            </label>
          </div>

          <!-- Submit Button -->
          <div>
            <button 
              type="submit" 
              [disabled]="isLoading || !loginForm.valid"
              class="w-full btn btn-primary py-3 flex justify-center items-center">
              @if (isLoading) {
                <span class="mr-2">
                  <span class="animate-spin inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full"></span>
                </span>
              }
              Sign in
            </button>
          </div>
        </form>
      </div>
    </div>
  `
})
export class LoginComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);

  loginForm: FormGroup;
  isLoading = false;
  showPassword = false;
  error: string | null = null;

  constructor() {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required]],
      password: ['', [Validators.required]],
      rememberMe: [false]
    });
  }

  isFieldInvalid(field: string): boolean {
    const formControl = this.loginForm.get(field);
    return formControl !== null && formControl.invalid && (formControl.dirty || formControl.touched);
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      this.isLoading = true;
      this.error = null;

      // Simulate API call
      setTimeout(() => {
        const { email, password } = this.loginForm.value;
        const success = this.authService.login(email, password);

        if (success) {
          this.router.navigate(['/dashboard']);
        } else {
          this.error = 'Invalid email or password. Please try again.';
        }
        this.isLoading = false;
      }, 1000);
    } else {
      this.loginForm.markAllAsTouched();
    }
  }
}
